name: Deploy Functions
on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SERVICE_ACCOUNT_EMAIL: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  FIRESTORE_DATABASE: onairlog

jobs:
  deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function:
          - Sync
          - Notify

    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - run: go mod vendor
      - name: Deploy ${{ matrix.function }}
        run: ./scripts/deploy-function.sh ${{ matrix.function }}
